#!/bin/bash

echo 'Formating files before commit'
staged_files=$(git diff --name-only --cached | tr '\n' ' ')
dotnet format --include $staged_files
git add $staged_files
echo 'Files formated successfully'
